# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

stripe: &stripe
  stripe_publishable_key: pk_test_i696lP8tLyP1ktDMvp4ndQaZ
  stripe_secret_key: sk_test_AzjZkp7nhq5R5SH6dySSKnpF
  stripe_client_id: ca_AAAhAl8lsI4Rt7GIEnTbSFPsZbZFC6Nh
  fee_percentage: 0

development:
  <<: *stripe
  secret_key_base: b87cf2e3e5ac58bf253f8c0bfc33b57037df1616ded015d2f059ca04b88154154b66b6639b49afe6db2fb438a00d696f73bb0bdeed27e0e8a60a30557900026f

test:
  <<: *stripe
  secret_key_base: 396d7fda82cf12e2ab68034753b250c20067317d2a4b053e2c40c5243cb14ff2cb1902044243e63aeb77fac3d36f14910b7bf356bbb639cb591b9f6d18c07348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *stripe
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
